apiVersion: apps/v1
kind: Deployment
metadata
  name: myweb-deploy
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: hys0254/mywebapp
        

---

apiVersion: v1
kind: Service
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: myweb
